name: GH-Actions

on:
  push:
    branches:
      - '*' # matches every branch that doesn't contain a '/'
      - '*/*' # matches every branch containing a single '/'
      - '**' # matches every branch
      - '**/**' # matches every branch
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        cypress:
          - working_directory: packages/apps/auth
          - working_directory: packages/apps/auth-e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress tests
        uses: ./
        with:
          working-directory: ${{ matrix.cypress.working_directory }}
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:3000'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
          name: With server
